In [3]:
import numpy as np
arra=np.array([1,2,3,4])
print(arra)
print(arra.ndim)


[1 2 3 4]
1


In [5]:
l=np.array([[1,2,3],[5,6,7]])
print(l)

[[1 2 3]
 [5 6 7]]


In [6]:
print(l)

[[1 2 3]
 [5 6 7]]


In [12]:
kl=np.array([1,2])
print(kl)

[1 2]
