In [1]:
import pandas as pd
import numpy as np


In [3]:
pd.__version__

'1.4.2'

In [5]:
pd.options.display.float_format='{:.2f}'.format

In [18]:
np.set_printoptions(precision=1)

In [20]:
r1=np.random.rand(2,5)*10
r1

array([[0.3, 8.8, 8.4, 9.5, 1.4],
       [7.9, 8.4, 7.6, 7.2, 6.9]])

In [21]:
r2=np.random.rand(2,5)*-1
r2

array([[-0.2, -0.5, -0.7, -0.9, -0.7],
       [-0.6, -0.7, -0.5, -0.7, -0.4]])

In [22]:
np.concatenate([r1,r2])

array([[ 0.3,  8.8,  8.4,  9.5,  1.4],
       [ 7.9,  8.4,  7.6,  7.2,  6.9],
       [-0.2, -0.5, -0.7, -0.9, -0.7],
       [-0.6, -0.7, -0.5, -0.7, -0.4]])

In [23]:
np.concatenate([r1,r2]).shape

(4, 5)

In [27]:
np.concatenate([r1,r2],axis=1)

array([[ 0.3,  8.8,  8.4,  9.5,  1.4, -0.2, -0.5, -0.7, -0.9, -0.7],
       [ 7.9,  8.4,  7.6,  7.2,  6.9, -0.6, -0.7, -0.5, -0.7, -0.4]])

In [25]:
np.concatenate([r1,r2],axis=1).shape

(2, 10)

r1

In [31]:
r1

array([[0.3, 8.8, 8.4, 9.5, 1.4],
       [7.9, 8.4, 7.6, 7.2, 6.9]])

In [41]:
s1=pd.Series(r1[0],index=['a','b','c','d','e'])
s1

a   0.26
b   8.77
c   8.38
d   9.48
e   1.39
dtype: float64

In [52]:
s2=pd.Series(r2[0],index=['f','g','h','i','a'])
s2

f   -0.20
g   -0.46
h   -0.71
i   -0.88
a   -0.67
dtype: float64

In [53]:
pd.concat([s1,s2])

a    0.26
b    8.77
c    8.38
d    9.48
e    1.39
f   -0.20
g   -0.46
h   -0.71
i   -0.88
a   -0.67
dtype: float64

In [54]:
pd.concat([s1,s2],axis=1)

0     1
a 0.26 -0.67
b 8.77   NaN
c 8.38   NaN
d 9.48   NaN
e 1.39   NaN
f  NaN -0.20
g  NaN -0.46
h  NaN -0.71
i  NaN -0.88

In [ ]:
pd.concat([s1,s2])

In [55]:
#elimina los indices ejemplo eleimiino el abcd etc por 0,1,2,3,4
s1.reset_index(drop=True)

0   0.26
1   8.77
2   8.38
3   9.48
4   1.39
dtype: float64

In [57]:
#indices del s1 numeros y indeces s2 letras
pd.concat([s1.reset_index(drop=True),s2],axis=1)

0     1
0 0.26   NaN
1 8.77   NaN
2 8.38   NaN
3 9.48   NaN
4 1.39   NaN
f  NaN -0.20
g  NaN -0.46
h  NaN -0.71
i  NaN -0.88
a  NaN -0.67

In [60]:
df1= pd.DataFrame(np.random.rand(3,2)*10,columns=['a','b'])
df1

a    b
0 3.72 7.22
1 8.65 1.09
2 3.17 0.16

In [61]:
df2= pd.DataFrame(np.random.rand(3,2)*10,columns=['a','b'],index=[2,3,4])
df2

a    b
2 7.49 0.34
3 0.27 6.97
4 7.94 4.66

In [62]:
pd.concat([df1,df2])

a    b
0 3.72 7.22
1 8.65 1.09
2 3.17 0.16
2 7.49 0.34
3 0.27 6.97
4 7.94 4.66

In [63]:
pd.concat([df1,df2],axis=1)

a    b    a    b
0 3.72 7.22  NaN  NaN
1 8.65 1.09  NaN  NaN
2 3.17 0.16 7.49 0.34
3  NaN  NaN 0.27 6.97
4  NaN  NaN 7.94 4.66

In [65]:
#une apratir de indices compartidos en este caso el indice 2
pd.concat([df1,df2],axis=1, join='inner')

a    b    a    b
2 3.17 0.16 7.49 0.34

In [66]:
df1.append(df2)

/tmp/ipykernel_16003/3062608662.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1.append(df2)


a    b
0 3.72 7.22
1 8.65 1.09
2 3.17 0.16
2 7.49 0.34
3 0.27 6.97
4 7.94 4.66

In [67]:
df1.append(df2).append(df2)

/tmp/ipykernel_16003/4259679585.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1.append(df2).append(df2)
/tmp/ipykernel_16003/4259679585.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1.append(df2).append(df2)


a    b
0 3.72 7.22
1 8.65 1.09
2 3.17 0.16
2 7.49 0.34
3 0.27 6.97
4 7.94 4.66
2 7.49 0.34
3 0.27 6.97
4 7.94 4.66

In [69]:
df1

a    b
0 3.72 7.22
1 8.65 1.09
2 3.17 0.16

In [68]:
#traspuesta donde esta la columnas a a las filas y viceversa
df1.T

0    1    2
a 3.72 8.65 3.17
b 7.22 1.09 0.16