In [2]:
import pandas as pd
import numpy as np

inicio = int(input('Introduce el año inicial: '))
fin = int(input('Introduce el año final: '))
ventas = {}
for i in range(inicio, fin+1):
    ventas[i] = float(input('Introduce las ventas del año ' + str(i) +': '))
ventas = pd.Series(ventas)
print('Ventas\n', ventas)
print('Ventas con descuento\n', ventas*0.9)


Introduce el año inicial: 1
Introduce el año final: 2
Introduce las ventas del año 1: 3
Introduce las ventas del año 2: 4
Ventas
 1    3.0
2    4.0
dtype: float64
Ventas con descuento
 1    2.7
2    3.6
dtype: float64


In [22]:

one= np.array([2,3,4])
print(one)
print(type(one))
print(one.ndim)

[2 3 4]
<class 'numpy.ndarray'>
1


In [23]:
dos= np.array([[2,3,4],[6,7,8]])
print(dos)
print(type(dos))
print(dos.ndim)

[[2 3 4]
 [6 7 8]]
<class 'numpy.ndarray'>
2


In [24]:
tres= np.array([[[1,2,3],[11,-2,-3]],[[4,5,6],[-4,-5,-6]]])
print(tres)
print(type(tres))
print(tres.ndim)

[[[ 1  2  3]
  [11 -2 -3]]

 [[ 4  5  6]
  [-4 -5 -6]]]
<class 'numpy.ndarray'>
3


In [25]:
print(tres[0,0,0])

1


In [26]:
print(tres[1,1])

[-4 -5 -6]


In [27]:
tt= np.array([[[1,2,3],[11,-2,-3]],[[4,5,6],[-4,-5,-6]]])
print(tt[0,1])

[11 -2 -3]


In [28]:
dosarray= np.array([[1,2,3],[4,5,6]])
for x in dosarray:
    print(x)

[1 2 3]
[4 5 6]


In [29]:
for y in dosarray:
    for k in y:
        print(k)

1
2
3
4
5
6


In [30]:
g= np.array([[[1,2,3],[11,-2,-3]],[[4,5,6],[-4,-5,-6]]])
for i in g:
    for x in i:
        for j in x:
            print(j)

1
2
3
11
-2
-3
4
5
6
-4
-5
-6


In [113]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [115]:
np.ones(3)

array([1., 1., 1.])

In [112]:
print(g.ndim)

3


In [31]:
zeroarray=np.zeros(10)
print(zeroarray)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [32]:
zeroarray= zeroarray.astype(int)
print(zeroarray)
                        

[0 0 0 0 0 0 0 0 0 0]


In [33]:
onesArray= np.ones(10)
print(onesArray)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [139]:
prefillarray= np.full(10,0)
print(prefillarray)

[0 0 0 0 0 0 0 0 0 0]


In [35]:
matrix= np.array([[1,2,3],[4,5,6]])
print(matrix)
print()
print(matrix+2)

[[1 2 3]
 [4 5 6]]

[[3 4 5]
 [6 7 8]]


In [36]:
print(matrix-2)

[[-1  0  1]
 [ 2  3  4]]


In [37]:
print(matrix+2)

[[3 4 5]
 [6 7 8]]


In [38]:
print(matrix/2)
print(matrix)

[[0.5 1.  1.5]
 [2.  2.5 3. ]]
[[1 2 3]
 [4 5 6]]


In [39]:
print(matrix**2)

[[ 1  4  9]
 [16 25 36]]


In [40]:
numpy.transponer 

NameError: name 'numpy' is not defined

In [41]:

print(matrix.T)

[[1 4]
 [2 5]
 [3 6]]


In [42]:
matrix11=np.array([[1,2,3],[4,5,6]])
print(matrix11)

[[1 2 3]
 [4 5 6]]


In [43]:
matrix22=np.array([[-1,-2,-3],[-4,-5,-6]])
print(matrix22)

[[-1 -2 -3]
 [-4 -5 -6]]


In [44]:
print(matrix11 + matrix22)

[[0 0 0]
 [0 0 0]]


In [45]:
print(matrix11 - matrix22)

[[ 2  4  6]
 [ 8 10 12]]


In [46]:
print(matrix11 / matrix22)

[[-1. -1. -1.]
 [-1. -1. -1.]]


In [47]:
print(matrix11 // matrix22)

[[-1 -1 -1]
 [-1 -1 -1]]


In [48]:
matrixk=np.array([[1,2,3],[4,5,6],[0,0,0]])
print(matrixk)

[[1 2 3]
 [4 5 6]
 [0 0 0]]


In [49]:
matrixl=np.array([[-1,-2,-3],[-4,-5,-6],[0,0,0]])
print(matrixl)

[[-1 -2 -3]
 [-4 -5 -6]
 [ 0  0  0]]


In [50]:
print(matrixl,matrixk)

[[-1 -2 -3]
 [-4 -5 -6]
 [ 0  0  0]] [[1 2 3]
 [4 5 6]
 [0 0 0]]


In [51]:
np.matmul(matrixk,matrixl)

array([[ -9, -12, -15],
       [-24, -33, -42],
       [  0,   0,   0]])

In [52]:
a= np.array([1,2])
b= np.array([3,4])
resulatado= np.dot(a,b)
print(resulatado)

11


In [53]:
minimo = np.array([10,4,5])
np.min(minimo)

4

In [54]:
np.sum(minimo)

19

In [55]:
print(sum(minimo))

19


In [56]:
np.max(minimo)

10

In [57]:
print(max(minimo))

10


In [58]:
np.mean(minimo)

6.333333333333333

In [59]:
np.std(minimo)

2.6246692913372702

In [60]:
desviacion= np.array([6,2,3,1])
print(desviacion)
np.std(desviacion)

[6 2 3 1]


1.8708286933869707

In [61]:
print(desviacion)


[6 2 3 1]


In [62]:
vida= np.array([1,2,3])
print(vida)

[1 2 3]


In [63]:
print(vida.ndim)

1


In [64]:
doss=np.array([[10,20,30],[50,60,70]])
print(doss.ndim)

2


In [71]:
tress=np.array([[[11,22,33],[44,55,66]],[[88,99,90],[77,67,87]]])
print(tress)

[[[11 22 33]
  [44 55 66]]

 [[88 99 90]
  [77 67 87]]]


In [72]:
print(tress.ndim)

3


In [73]:
print(tress[0,1])

[44 55 66]


In [75]:
print(tress[1,0])

[88 99 90]


In [76]:
print(tress+1)

[[[ 12  23  34]
  [ 45  56  67]]

 [[ 89 100  91]
  [ 78  68  88]]]


In [78]:
print(tress-2)

[[[ 9 20 31]
  [42 53 64]]

 [[86 97 88]
  [75 65 85]]]


In [100]:
matrixa=np.array([[1,2,3],[4,5,6]])
print(matrixa)


[[1 2 3]
 [4 5 6]]


In [92]:
print(matrixa.ndim)

2


In [98]:
matrixb=np.array([[-1,-2,-3],[-4,-5,-6]])
print(matrixb)

[[-1 -2 -3]
 [-4 -5 -6]]


In [101]:
print(matrixa + matrixb)

[[0 0 0]
 [0 0 0]]


In [109]:
np.std(matrixa)


1.707825127659933

In [110]:
np.mean(matrixa)

3.5

In [118]:
h=np.zeros(4)
h=h.astype(int)
print(h)

[0 0 0 0]


In [119]:
unos= np.ones(4)
print(unos)
unos=unos.astype(int)
print(unos)

[1. 1. 1. 1.]
[1 1 1 1]


In [120]:
arre=np.array([1,2,3,4,5,6])
print(arre)

[1 2 3 4 5 6]


In [124]:
arre=np.arange(12,20)
print(arre)

[12 13 14 15 16 17 18 19]


In [126]:
print(arre[2:5])

[14 15 16 17]


In [134]:
desor=np.array([5,2,7,2,0])


In [136]:
orden=desor.sort()
print(orden)

None
