In [3]:
import pandas as pd
import numpy as np

inicio = int(input('Introduce el año inicial: '))
fin = int(input('Introduce el año final: '))
ventas = {}
for i in range(inicio, fin+1):
    ventas[i] = float(input('Introduce las ventas del año ' + str(i) +': '))
ventas = pd.Series(ventas)
print('Ventas\n', ventas)
print('Ventas con descuento\n', ventas*0.9)


Introduce el año inicial: 1
Introduce el año final: 2
Introduce las ventas del año 1: 3
Introduce las ventas del año 2: 4
Ventas
 1    3.0
2    4.0
dtype: float64
Ventas con descuento
 1    2.7
2    3.6
dtype: float64


In [21]:

one= np.array([2,3,4])
print(one)
print(type(one))
print(one.ndim)

[2 3 4]
<class 'numpy.ndarray'>
1


In [13]:
dos= np.array([[2,3,4],[6,7,8]])
print(dos)
print(type(dos))
print(dos.ndim)

[[2 3 4]
 [6 7 8]]
<class 'numpy.ndarray'>
2


In [20]:
tres= np.array([[[1,2,3],[11,-2,-3]],[[4,5,6],[-4,-5,-6]]])
print(tres)
print(type(tres))
print(tres.ndim)

[[[ 1  2  3]
  [ 1  2  3]]

 [[ 4  5  6]
  [-4 -5 -6]]]
<class 'numpy.ndarray'>
3


In [26]:
print(tres[0,0,0])

1


In [30]:
print(tres[1,1])

[-4 -5 -6]


In [32]:
tt= np.array([[[1,2,3],[11,-2,-3]],[[4,5,6],[-4,-5,-6]]])
print(tt[0,1])

[11 -2 -3]


In [34]:
dosarray= np.array([[1,2,3],[4,5,6]])
for x in dosarray:
    print(x)

[1 2 3]
[4 5 6]


In [35]:
for y in dosarray:
    for k in y:
        print(k)

1
2
3
4
5
6


In [40]:
g= np.array([[[1,2,3],[11,-2,-3]],[[4,5,6],[-4,-5,-6]]])
for i in g:
    for x in i:
        for j in x:
            print(j)

1
2
3
11
-2
-3
4
5
6
-4
-5
-6


In [41]:
zeroarray=np.zeros(10)
print(zeroarray)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [42]:
zeroarray= zeroarray.astype(int)
print(zeroarray)
                        

[0 0 0 0 0 0 0 0 0 0]


In [44]:
onesArray= np.ones(10)
print(onesArray)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [46]:
prefillarray= np.full(1,4)
print(prefillarray)

[4]


In [51]:
matrix= np.array([[1,2,3],[4,5,6]])
print(matrix)
print(matrix+2)

[[1 2 3]
 [4 5 6]]
[[3 4 5]
 [6 7 8]]


In [55]:
print(matrix-2)

[[-1  0  1]
 [ 2  3  4]]


In [53]:
print(matrix+2)

[[3 4 5]
 [6 7 8]]


In [56]:
print(matrix/2)
print(matrix)

[[0.5 1.  1.5]
 [2.  2.5 3. ]]
[[1 2 3]
 [4 5 6]]


In [57]:
print(matrix**2)

[[ 1  4  9]
 [16 25 36]]


In [58]:

print(matrix.T)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
numpy.transponer 