In [57]:
import numpy as np


In [58]:
a = np.array([1, 2, 3])

In [59]:
print(a)

[1 2 3]


In [60]:
np.zeros(2)

array([0., 0.])

In [61]:
np.ones(2)

array([1., 1.])

In [62]:
# Create an empty array with 2 elements
np.empty(2) 

array([1., 1.])

In [63]:
np.empty(2) 

array([1., 1.])

In [64]:
#uede crear una matriz con un rango de elementos:
np.arange(4)


array([0, 1, 2, 3])

In [65]:
#rango de intervalos espaciados uniformemente. Para hacer esto, especificará el primer número , el último número y el tamaño del paso .
np.arange(2,50,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [66]:
#También puede usar np.linspace()para crear una matriz con valores que están espaciados linealmente en un intervalo específico:
np.linspace(0,10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [67]:
#i bien el tipo de datos predeterminado es de punto flotante ( np.float64), puede especificar explícitamente qué tipo de datos desea usar la dtypepalabra clave.
np.ones(2, dtype=np.int64)

array([1, 1])

In [68]:
#Ordenar un elemento es simple con np.sort(). Puede especificar el eje, el tipo y el orden cuando llama a la función.
aa=np.array([2,1,4,6,9,7,8])

In [69]:
np.sort(aa)

array([1, 2, 4, 6, 7, 8, 9])

In [70]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [71]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [72]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [73]:
array_example.ndim

3

In [74]:
#numeot total de elementos
array_example.size

24

In [75]:
#Y para encontrar la forma de su matriz, ejecute:
array_example.shape


(3, 2, 4)

In [76]:
aaa=np.array([[1,2,3,4,5],[7,8,9,10,11]])
print(aaa)

[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]


In [77]:
aaa.shape

(2, 5)

In [78]:
aaa.ndim

2

In [79]:
hh= np.array([[[0, 1, 2, 3, 4],[5, 6, 7, 8, 9],[10, 11, 12, 13, 14],[15, 16, 17, 18, 19]],
        [[20, 21, 22, 23, 24],[25, 26, 27, 28, 29],[40, 41, 42, 43, 44],[67, 45, 46, 47, 46]],
        [[50, 51, 52, 33, 34],[34, 35, 36, 37, 36],[40, 41, 42, 43, 44],[67, 45, 46, 47, 46]]])

In [80]:
hh

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [40, 41, 42, 43, 44],
        [67, 45, 46, 47, 46]],

       [[50, 51, 52, 33, 34],
        [34, 35, 36, 37, 36],
        [40, 41, 42, 43, 44],
        [67, 45, 46, 47, 46]]])

In [81]:
np.shape(hh)


(3, 4, 5)

In [82]:
s=np.array([[1,2,3],[4,5,6]])

In [83]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [84]:
array_example.ndim

3

In [85]:
array_example.size

24

In [86]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [87]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [88]:
#Con np.reshape, puede especificar algunos parámetros opcionales:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [89]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [90]:
#Puede usar np.newaxispara agregar un nuevo eje:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [91]:
a2

array([[1, 2, 3, 4, 5, 6]])

In [92]:
a2.ndim


2

In [93]:
d5=np.array([[[[1,2]]]])
d5.ndim

4

In [103]:
ceros=np.zeros((4,5),dtype='int')
ceros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [104]:
empty=np.empty((5,6),dtype='int')
empty

array([[    139742105492688,      94197853926960,                   0,
                          0,                   0, 4189022153932546683],
       [3471486078910865952, 4193188065225944374, 3833739988843508020,
        2318265678939828281, 2478221553439042850, 3835151968702177338],
       [3761176615228761445, 3762539103408775728, 3775484581381158196,
        8440344025573373494, 2478507435169572211, 7958535038077902906],
       [8296228837497597281, 4189032028197581669, 3834029363103670816,
        3545570297039106914, 3846748517878018614, 3546691566286682210],
       [8317341608397922658, 4189022137156394855, 8391722768137527840,
        8315181416903237477, 8243124581912289908, 2459029316100385139]])

In [106]:
alazar=np.random.random((3,4))
alazar

array([[0.45982226, 0.72600539, 0.29029611, 0.77639616],
       [0.89974686, 0.34270574, 0.88024752, 0.88540032],
       [0.05876273, 0.61054115, 0.90892999, 0.19921314]])

In [112]:
enterosazar=np.random.randint(0,2, size=(3,4))
enterosazar

array([[0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0]])

In [116]:
enterosazar.sum()

3

In [118]:
#suma de las columnas
enterosazar.sum(axis=0)

array([1, 0, 2, 0])

In [120]:
#suma de las filas
enterosazar.sum(axis=1)

array([1, 1, 1])

In [123]:
#valor maximo por cada columna
enterosazar.max(axis=0)

array([1, 0, 1, 0])

In [125]:
#valor maximo de cada fila
enterosazar.max(axis=1)


array([1, 1, 1])

In [128]:
enterosazar.max()

1

In [134]:
ente=np.random.randint(0,34, size=(3,4))
#gurardar la posicion donde esta el minimo y maximo con array.argmax
ente


array([[14,  9, 12, 19],
       [ 8,  5,  2, 18],
       [29,  0, 27, 25]])

In [136]:
#posicion del array donde esta el valor maximo
ente.argmax()

8

In [138]:
#posiicon del valor donde esta el valor minimo
ente.argmin()

9

In [140]:
#valor del promedio de array
ente.mean()

14.0

In [142]:
#valor dela devioacion estandar
ente.std()

9.318440498996242